baseurl = "https://juanjollanos.cl"
title = "Juanjo Llanos"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Juan José Llanos Correa"
  info = "Full Stack Software Engineer"
  description = "Juan Llanos personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/linkedin_photo.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2018

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customSCSS = ["scss/custom.scss"]
  #customCSS = ["css/carousel.css"]
  #customJS = ["js/carousel.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Ukarus"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/juan-jos%C3%A9-llanos-correa-706951159/"
[[params.social]]
  name = "Itch.io"
  icon = "fa fa-gamepad fa-2x"
  weight = 2
  url = "https://blonjon.itch.io/"

# Menu links
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "en/projects/"
[[menu.main]]
  name = "Games"
  weight = 2
  url = "en/games/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "en/about"